name = "Divine Comedy"
author = "Wolkenz"
version = "1.1.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cdd6ae8755b35f17ac0f9045615faef68e64931ad01a6991e34de66274c0a1f4"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
