name = "Divine Comedy"
author = "Wolkenz"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2384da0edcaa3f33564238ecec570ce4ed91b5728b6fbf69729316556c420377"

[versions]
fabric = "0.18.4"
minecraft = "1.20.1"
