[display]
style = "CLASSIC"

[display.itemEntry]
display = true
displayTotalAmount = true
useItemFormatting = true
color = 16777215
italic = false

[display.aggregatedEntry]
display = true
color = 16777215
italic = true

[display.experienceEntry]
display = true
color = 5635925
italic = false
[layout]
anchor = "BOTTOM_RIGHT"
anchorPixelOffset = 3
anchorPercentOffset = 10
scale = 100
separation = 3
lifetime = 6
displayCapacity = 9
queueCapacity = 9
[filter]
defaultItemPolicy = "ALLOW_ALL"
itemIdBlacklist = []
itemIdWhitelist = []
modIdBlacklist = []
modIdWhitelist = []
